owner: KastelApp
repo: uptime
sites:
  - name: Canary API
    url: https://canary-api.kastelapp.com
  - name: Canary Gateway
    url: https://dev-gateway.kastelapp.com
    expectedStatusCodes:
      - 200
      - 404
      - 400
  - name: Media Server
    url: https://media.kastelapp.com/ping
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kastel App
  introTitle: This is Kastel's Uptime Page!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: App
      href: https://kastelapp.com
